/**
 * Curated Construction Knowledge Bank Records
 * First-hand construction observations from London & South East projects.
 * Used by AI Planner, Content Engine, and Estimate Calibration.
 */

import { ConstructionKnowledgeRecord } from '@/types/knowledge-bank';

export const constructionKnowledgeBank: ConstructionKnowledgeRecord[] = [
  {
    id: 'kb-victorian-joist-undersizing',
    category: 'structural',
    title: 'Victorian Suspended Timber Floor Joist Undersizing & Sag',
    serviceSlugs: ['full-renovation', 'kitchen-renovation', 'extension'],
    propertyTypes: ['terraced', 'semi-detached'],
    propertyEras: ['victorian', 'edwardian'],
    boroughs: ['Ealing', 'Richmond', 'Chiswick', 'Harrow', 'Hammersmith', 'Wandsworth'],
    problemSummary: 'Excessive bounce, deflection, or slope in ground floor timber suspended joists before installing heavy modern kitchen islands or tiled screeds.',
    rootCause: '19th-century timber joists were sized for lightweight furniture without modern dead loads (quartz islands, cast iron radiators, porcelain floor tiles). Joist ends frequently suffer from wet rot where embedded in damp solid brick external walls.',
    howIdentifiedOnSite: 'Laser level floor survey and opening floorboards at wall plates during initial strip-out inspection.',
    warningSignsForHomeowners: [
      'Visible spring or bounce when walking across the centre of the room',
      'Gap between skirting boards and floorboards on party walls',
      'Cracking along ceiling plaster directly below first-floor rooms',
    ],
    tradeSolution: 'Sistering existing joists with C24 structural timbers bonded with structural polyurethane adhesive and through-bolted at 400mm centres. Installing telescopic subfloor air vents and DPC wrap to joist pockets.',
    whyThisSolution: 'Restores structural rigidity to span modern kitchen island loads without requiring full joist replacement or lowering ceiling heights.',
    recommendedMaterials: ['C24 Treated Graded Timber', 'M12 Coach Screws / Through Bolts', 'Schluter Ditra Uncoupling Mat for tiling'],
    materialsToAvoid: ['Standard untreated C16 softwood', 'Laying heavy porcelain tiles directly on flexing plywood without uncoupling'],
    tradeSequence: ['Carpentry sistering', 'Subfloor ventilation check', 'PIR thermal floor insulation', '18mm/22mm T&G Plywood deck', 'Uncoupling membrane', 'Final floor finish'],
    estimatedCostImpact: '+£1,200 – £2,400 per room',
    estimatedDelayImpact: '+2–4 days before first fix',
    riskIfIgnored: 'Cracked porcelain tiles, grout failure, kitchen island settlement, and long-term timber dry rot.',
    builderObservationQuote: 'On older London homes, we never lay a heavy kitchen island or stone floor without opening up the subfloor. A £1,500 joist reinforcement during first-fix saves a £10,000 floor failure 12 months down the line.',
    surveyorInspectionChecklist: [
      'Check subfloor air brick ventilation paths are not blocked by external patio raising',
      'Probe joist ends embedded in solid exterior masonry for moisture content (>18% requires timber treatment)',
      'Verify joist depth against current Part A structural span tables',
    ],
    frequentlyAskedCustomerQuestion: 'Why do we need to strengthen the floor if we are only replacing the kitchen units?',
    verifiedBuilderAnswer: 'A modern quartz kitchen island weighs between 300kg and 600kg in a concentrated 2m² footprint. Victorian suspended joists were never engineered for point loads of that magnitude without deflection.',
    verifiedBy: 'Lead Structural Project Manager - 22 yrs exp',
    approvedForPublicContent: true,
    isInternalOnly: false,
    dateAdded: '2026-08-28',
    lastVerified: '2026-08-28',
  },
  {
    id: 'kb-party-wall-shared-drainage',
    category: 'planning_regs',
    title: 'Thames Water Shared Drain Diversion on Rear Extensions',
    serviceSlugs: ['extension'],
    propertyTypes: ['terraced', 'semi-detached'],
    propertyEras: ['victorian', 'edwardian', '1930s'],
    boroughs: ['Ealing', 'Richmond', 'Chiswick', 'Harrow', 'Brent', 'Barnet'],
    problemSummary: 'Public/shared combined sewer running within 3 metres of proposed rear foundation excavation.',
    rootCause: 'Under the 2011 Private Sewers Transfer Regulations, any drain serving more than one property is legally owned by Thames Water. Building over or near requires formal Thames Water Build Over Agreement or diversion.',
    howIdentifiedOnSite: 'CCTV drainage survey from manhole inspection chamber and Thames Water asset mapping.',
    warningSignsForHomeowners: [
      'Manhole cover located within 3m of proposed rear patio or extension footprint',
      'Adjoining neighbour shares a continuous rear downpipe or foul drain',
    ],
    tradeSolution: 'CCTV survey to map exact depth and invert levels. If building over: bridge foundations with reinforced concrete lintels. If manhole falls inside the room: divert inspection chamber externally with airtight double-seal recessed cover or re-route run outside extension footprint.',
    whyThisSolution: 'Ensures full Thames Water Build Over Certificate sign-off and prevents sewer gas ingress or future excavation disruption inside the living room.',
    recommendedMaterials: ['110mm / 160mm PVC Underground Drainage Pipes', 'Clark-Drain airtight double-sealed recessed tray covers', 'High-density pea shingle pipe bedding'],
    materialsToAvoid: ['Leaving single-seal manhole covers beneath internal suspended timber floors'],
    tradeSequence: ['CCTV drainage survey', 'Thames Water Build Over submission', 'Drain excavation & pipe diversion', 'Concrete lintel bridging over pipes', 'Building control inspection', 'Backfill with pea gravel'],
    estimatedCostImpact: '+£1,500 – £3,500 (depending on diversion complexity)',
    estimatedDelayImpact: '+1–3 weeks for water authority approval (submitted during architectural phase)',
    riskIfIgnored: 'Building Control refusal of final completion certificate, inability to sell property without Build Over indemnity, and risk of sewer backup inside the home.',
    builderObservationQuote: 'Never start digging extension footings until you know exactly where the neighbour’s waste enters your pipe. Thames Water approvals take 10 working days if submitted early, but weeks if discovered after concrete is ordered.',
    surveyorInspectionChecklist: [
      'Run dye test from neighbour’s gullies to confirm shared sewer status',
      'Measure invert level of sewer to calculate minimum footing depth',
      'Verify minimum 500mm clearance between pile/strip foundations and sewer pipe',
    ],
    frequentlyAskedCustomerQuestion: 'Can we just tile over the manhole cover in our new kitchen?',
    verifiedBuilderAnswer: 'No, building regulations strictly prohibit inaccessible drainage inspection chambers inside habitable living areas. The chamber must either be relocated externally or fitted with an airtight double-seal access cover.',
    verifiedBy: 'Senior Technical Director - 26 yrs exp',
    approvedForPublicContent: true,
    isInternalOnly: false,
    dateAdded: '2026-08-28',
    lastVerified: '2026-08-28',
  },
  {
    id: 'kb-low-pressure-gravity-system',
    category: 'm_and_e',
    title: 'Gravity Feed Low Water Pressure vs Modern Multi-Bathroom Requirements',
    serviceSlugs: ['bathroom-renovation', 'full-renovation', 'loft-conversion'],
    propertyTypes: ['terraced', 'semi-detached', 'detached'],
    propertyEras: ['victorian', 'edwardian', '1930s'],
    boroughs: ['Ealing', 'Richmond', 'Chiswick', 'Harrow', 'Kingston'],
    problemSummary: 'Insufficient water flow rate and pressure when adding a loft en-suite or second master bathroom to an existing conventional boiler with cold water tank in the loft.',
    rootCause: 'Traditional gravity systems only deliver 0.2–0.5 bar pressure. Removing the loft tank for a conversion or adding high-flow walk-in rainfall showers causes pressure collapse when two taps run simultaneously.',
    howIdentifiedOnSite: 'Mains dynamic water pressure (bar) and flow rate (litres/min) testing at external boundary stopcock and internal kitchen riser.',
    warningSignsForHomeowners: [
      'Shower flow turns to a trickle if a toilet is flushed elsewhere in the house',
      'Cold water storage tank currently takes up valuable loft conversion floor area',
    ],
    tradeSolution: 'Upgrade to an Unvented Hot Water Cylinder (Megaflo / Joule) or High-Output System Boiler. If incoming street mains is under 20L/min, install an accumulator tank with cold water booster pump.',
    whyThisSolution: 'Delivers balanced 3.0 bar mains pressure to all showers and taps simultaneously on ground, first, and loft floors while clearing the roof void of header tanks.',
    recommendedMaterials: ['Megaflo Eco Stainless Steel Unvented Cylinder', 'Salamander / Stuart Turner HomeBoost pump', '22mm or 28mm primary copper pipework'],
    materialsToAvoid: ['Attempting to run two simultaneous thermostatic rainfall showers off an entry-level 24kW combi boiler with 15mm supply'],
    tradeSequence: ['Mains flow & pressure gauge test', 'Remove loft header tank during roof opening', 'First fix 22mm hot/cold distribution feeds', 'Install unvented cylinder in utility/cupboard', 'G3 Building Control sign-off'],
    estimatedCostImpact: '£3,500 – £6,000 for complete unvented cylinder and system boiler conversion',
    estimatedDelayImpact: 'Integrated into standard M&E first fix phase (no additional delay if planned)',
    riskIfIgnored: 'Lukewarm showers, inadequate water flow in loft bathrooms, and scalding risk from pressure drops.',
    builderObservationQuote: 'If you are adding a loft en-suite or second bathroom, check the incoming street flow rate before buying expensive shower valves. A high-end rainfall head is useless without the pressure to feed it.',
    surveyorInspectionChecklist: [
      'Measure dynamic flow rate with weir cup (minimum 18L/min needed for unvented cylinder)',
      'Check internal lead main pipework status (replace with 25mm MDPE if lead exists)',
      'Ensure dedicated discharge pipe (tundish) route to external drain for G3 unvented safety',
    ],
    frequentlyAskedCustomerQuestion: 'Can our existing combination boiler handle an extra loft bathroom?',
    verifiedBuilderAnswer: 'A standard combi heats water on demand and can only supply one shower at a time (approx. 10-12L/min). For 2+ bathrooms running concurrently, an unvented hot water cylinder is the professional standard.',
    verifiedBy: 'M&E Lead Project Engineer - 19 yrs exp',
    approvedForPublicContent: true,
    isInternalOnly: false,
    dateAdded: '2026-08-28',
    lastVerified: '2026-08-28',
  },
  {
    id: 'kb-solid-wall-internal-insulation-dewpoint',
    category: 'materials',
    title: 'Solid Brick Wall Internal Insulation & Condensation Dewpoint Control',
    serviceSlugs: ['full-renovation', 'extension'],
    propertyTypes: ['terraced', 'semi-detached'],
    propertyEras: ['victorian', 'edwardian', 'georgian'],
    boroughs: ['Ealing', 'Richmond', 'Chiswick', 'Harrow', 'Camden', 'Islington'],
    problemSummary: 'Trapped moisture, interstitial condensation, and hidden mould behind drylining when insulating single-skin 9-inch solid brick walls.',
    rootCause: 'Solid brick walls rely on breathability to dry outwards. Inappropriately fitting impermeable insulation without a continuous vapour barrier shifts the dewpoint to the brick-insulation interface, causing moisture build-up.',
    howIdentifiedOnSite: 'Moisture meter analysis of solid masonry and thermal bridge inspection during strip-out.',
    warningSignsForHomeowners: [
      'Musty damp smell behind fitted wardrobes on exterior solid walls',
      'Cold, damp feeling on external walls during winter months',
    ],
    tradeSolution: 'Treat external masonry pointing with breathable lime mortar. Install independent treated studwork with 25mm ventilated cavity or use breathable wood-fibre / aerogel insulation boards with intelligent variable vapour control layer (VCL) taped at all seams.',
    whyThisSolution: 'Dramatically improves EPC rating and warmth while preventing interstitial condensation and preserving the structural longevity of historical London brickwork.',
    recommendedMaterials: ['ProClima Intello Plus Variable VCL membrane', 'PIR Foil-Faced Insulation with taped joints or Steico Wood Fibre', 'Breathable NHL 3.5 Lime mortar'],
    materialsToAvoid: ['Fixing standard plasterboard directly to damp solid brickwork with dot-and-dab adhesive without treating underlying moisture'],
    tradeSequence: ['Masonry moisture check & repointing', 'DPM barrier at floor level', 'Treated timber/metal stud installation', 'Insulation fitting', 'Airtight VCL membrane taping', 'Plasterboard skim'],
    estimatedCostImpact: '£65 – £95 per m² of external wall area',
    estimatedDelayImpact: 'Concurrent with drylining phase',
    riskIfIgnored: 'Hidden toxic black mould, rotting timber joist ends embedded in walls, and blown plaster.',
    builderObservationQuote: 'Solid brick London homes need to breathe. We never seal a 120-year-old Victorian wall without managing the vapour barrier correctly. Done right, your heating bills drop by 40% with zero damp issues.',
    surveyorInspectionChecklist: [
      'Inspect external brick pointing condition (repair blown cement with breathable lime)',
      'Check high ground levels bridging the external DPC line',
      'Verify continuous air-tightness taping around window reveals and socket boxes',
    ],
    frequentlyAskedCustomerQuestion: 'Will insulating from the inside take away a lot of room space?',
    verifiedBuilderAnswer: 'High-performance PIR boards with integrated vapour barrier require only 50mm–65mm build-up, preserving your room proportions while transforming thermal comfort.',
    verifiedBy: 'Lead Conservation & Renovation Surveyor - 25 yrs exp',
    approvedForPublicContent: true,
    isInternalOnly: false,
    dateAdded: '2026-08-28',
    lastVerified: '2026-08-28',
  },
];
