import { CaseStudy } from '@/types';

export const caseStudiesData: CaseStudy[] = [
  {
    id: 'ealing-rear-extension',
    slug: 'ealing-contemporary-rear-extension',
    title: 'Contemporary Open-Plan Rear Extension & Kitchen',
    serviceSlug: 'extensions',
    projectType: 'Single Storey Rear Extension',
    location: 'Ealing, West London',
    completionYear: '2025',
    duration: '12 weeks',
    indicativeCost: '£85,000',
    customerObjective: 'Transform a 4-bedroom Victorian family home in Ealing by creating an expansive 38m² open-plan kitchen, dining, and living extension connecting seamlessly to the landscaped rear garden.',
    challenge: 'Victorian London stock brickwork required underpinning and existing drainage needed to be diverted beneath the proposed 38m² reinforced floor slab without disrupting neighbouring boundary lines.',
    solution: 'Engineered a concealed steel goalpost structure supporting a 6-metre clear span, flush floor levels to the patio, two large flat rooflights, and 4.8m powder-coated aluminium slimline sliders.',
    coverImage: '/images/case-studies/ealing-rear-extension.png',
    beforeImages: [
      '/images/case-studies/ealing-rear-extension.png',
    ],
    progressImages: [
      '/images/case-studies/ealing-rear-extension.png',
    ],
    afterImages: [
      '/images/case-studies/ealing-rear-extension.png',
      '/images/case-studies/chiswick-kitchen.png',
    ],
    highlights: [
      '38m² open-plan ground floor extension',
      'Floor-to-ceiling slimline aluminium sliding doors',
      'Integrated roof lantern bringing natural light deep into living zones',
      'Underfloor water heating throughout and bespoke kitchen island',
    ],
    testimonial: {
      quote: 'Apex delivered exactly what they promised on time and within our agreed budget. The open plan space has completely transformed how our family lives every day.',
      author: 'Marcus & Sophie T.',
      location: 'Ealing, W5',
    },
  },
  {
    id: 'richmond-victorian-renovation',
    slug: 'richmond-full-period-home-renovation',
    title: 'Victorian Villa Full Renovation & Loft Suite',
    serviceSlug: 'renovations',
    projectType: 'Full House Renovation & Loft',
    location: 'Richmond, South West London',
    completionYear: '2025',
    duration: '20 weeks',
    indicativeCost: '£175,000',
    customerObjective: 'Full architectural modernization of an expansive 5-bedroom Victorian villa in Richmond, restoring original period features while adding a luxury master bedroom suite, modern bathrooms, and rear dormer loft conversion.',
    challenge: 'Significant structural timber degradation across ground and first floors requiring complete structural joist replacement, new steel ring-beams, and full electrical and plumbing overhaul.',
    solution: 'Reinforced the floor diaphragms, fully insulated external walls with breathable aerogel boards, restored decorative cornicing, and constructed a dormer loft master suite with en-suite wet room and bespoke dressing room.',
    coverImage: '/images/case-studies/richmond-victorian-villa.png',
    beforeImages: [
      '/images/case-studies/richmond-victorian-villa.png',
    ],
    progressImages: [
      '/images/case-studies/richmond-victorian-villa.png',
    ],
    afterImages: [
      '/images/case-studies/richmond-victorian-villa.png',
      '/images/case-studies/richmond-master-suite.jpg',
      '/images/case-studies/loft-suite.png',
      '/images/case-studies/bathroom.png',
    ],
    highlights: [
      'Complete 5-bedroom interior modernization & layout reconfiguration',
      'New dormer loft master suite with en-suite wet room',
      'Heritage sash window replacements with acoustic double glazing',
      'Full Part P electrical rewiring and unvented cylinder heating upgrade',
    ],
    testimonial: {
      quote: 'Their attention to detail on period plasterwork combined with crisp modern bathrooms was second to none. Truly outstanding project management from start to finish.',
      author: 'David & Helena K.',
      location: 'Richmond, TW9',
    },
  },
  {
    id: 'chiswick-luxury-kitchen',
    slug: 'chiswick-bespoke-kitchen-knockthrough',
    title: 'Architectural Kitchen Knockthrough & Living Zone',
    serviceSlug: 'kitchen-renovations',
    projectType: 'Kitchen Renovation',
    location: 'Chiswick, London',
    completionYear: '2024',
    duration: '5 weeks',
    indicativeCost: '£42,000',
    customerObjective: 'Reconfigure the ground floor of a 4-bedroom Edwardian townhouse in Chiswick, removing dividing load-bearing walls to construct a bespoke open-plan chef kitchen with central entertaining island.',
    challenge: 'Load-bearing masonry supporting two upper floors required installation of a heavy universal column and beam concealed flush within the ceiling void.',
    solution: 'Designed and installed flush structural steelwork, fitted bespoke hand-painted shaker units, installed Calacatta Gold quartz surfaces, and laid chevron engineered oak flooring.',
    coverImage: '/images/case-studies/chiswick-kitchen.png',
    beforeImages: [
      '/images/case-studies/chiswick-kitchen.png',
    ],
    progressImages: [
      '/images/case-studies/chiswick-kitchen.png',
    ],
    afterImages: [
      '/images/case-studies/chiswick-kitchen.png',
      '/images/services/garage-conversions.png',
    ],
    highlights: [
      'Concealed flush structural steelwork',
      '3.2-metre quartz waterfall island with seating for 5',
      'Smart zoned mood lighting and wine cooler integration',
      'Engineered herringbone timber flooring',
    ],
    testimonial: {
      quote: 'Clean, courteous, and remarkably quick. The kitchen is now the showpiece of our entire home.',
      author: 'Claire P.',
      location: 'Chiswick, W4',
    },
  },
  {
    id: 'kew-cedar-garden-studio',
    slug: 'kew-architectural-garden-studio',
    title: 'Bespoke Western Red Cedar Garden Office & Studio',
    serviceSlug: 'garden-rooms',
    projectType: 'Garden Room',
    location: 'Kew, Surrey',
    completionYear: '2024',
    duration: '4 weeks',
    indicativeCost: '£28,000',
    customerObjective: 'Design and construct a high-specification insulated garden studio and complete outdoor living patio for a 5-bedroom suburban residence in Kew.',
    challenge: 'Limited side-access to garden requiring compact material delivery and zero damage to existing ornamental lawn and trees.',
    solution: 'Installed zero-impact ground screw foundation system, double acoustic stud walls with Green Glue damping, Western Red Cedar secret-fixed cladding, and CAT6 hardwired ethernet.',
    coverImage: '/images/case-studies/kew-garden-studio.png',
    beforeImages: [
      '/images/case-studies/kew-garden-studio.png',
    ],
    progressImages: [
      '/images/case-studies/kew-garden-studio.png',
    ],
    afterImages: [
      '/images/case-studies/kew-garden-studio.png',
      '/images/services/landscaping.png',
    ],
    highlights: [
      '24m² insulated internal floor area',
      'Acoustic decoupling system for quiet working and recording',
      'Anthracite aluminium sliding doors and picture window',
      'Wi-Fi controlled infrared radiant heating panel',
    ],
    testimonial: {
      quote: 'The craftsmanship on the cedar cladding is flawless. Working from the garden has completely eliminated commute stress.',
      author: 'Jonathan R.',
      location: 'Kew Gardens, TW9',
    },
  },
];
