import { ServiceDefinition } from '@/types';

export const servicesData: ServiceDefinition[] = [
  {
    id: 'extensions',
    slug: 'extensions',
    title: 'House Extensions',
    shortDescription: 'Rear, side-return, and double-storey extensions designed to transform your ground floor living space.',
    fullDescription:
      'Expand your home and create light-filled, open-plan living with an architectural extension. From kitchen-diners with floor-to-ceiling bifold doors to generous double-storey additions, our in-house team handles architectural design, planning permissions, structural engineering, and complete build execution.',
    iconName: 'Home',
    heroImage: '/images/services/house-extensions.png',
    indicativePriceRange: '£55,000 – £140,000+',
    typicalDuration: '10 – 16 weeks',
    keyBenefits: [
      'Dramatic increase in open-plan ground floor living space',
      'Seamless connection to rear gardens with aluminium bifolds or sliders',
      'Adds substantial market value to residential properties',
      'Turnkey delivery: design, structural steelwork, glazing, and fit-out',
    ],
    stages: [
      { title: 'Architectural Design & Feasibility', description: 'Site survey, 3D conceptual designs, and structural viability assessments.' },
      { title: 'Planning & Building Control', description: 'Permitted Development confirmation or full planning application submission.' },
      { title: 'Groundworks & Foundations', description: 'Excavation, concrete strip/trench footings, drainage diversion, and slab installation.' },
      { title: 'Structural Steel & Shell', description: 'Steel beam installation (RSJs), cavity masonry, insulation, and roof construction.' },
      { title: 'Weatherproofing & Glazing', description: 'Roof membranes, skylights, and bespoke glazing installation.' },
      { title: 'First & Second Fix Trades', description: 'Electrics, plumbing, underfloor heating, plastering, kitchen installation, and finishing.' },
    ],
    planningGuidance: 'Many single-storey rear extensions up to 4m (or 8m on detached homes with Prior Approval) fall under Permitted Development rights. We manage all lawful development certificates and planning submissions.',
    costDrivers: ['Extension footprint (m²)', 'Single vs double storey', 'Structural opening width', 'Roof lantern & glazing specifications', 'Kitchen & bathroom inclusion'],
    faqs: [
      { question: 'Can I live in the property during the extension build?', answer: 'In most single-storey rear extensions, homeowners remain in the property. We install secure, dust-tight temporary partition screening to protect your living areas.' },
      { question: 'Do I need a Party Wall agreement?', answer: 'If building on or within 3 metres of an adjoining boundary and excavating below their foundations, Party Wall notices are legally required. We manage notices and surveyors on your behalf.' },
      { question: 'How long does an extension take to build?', answer: 'A standard 30m² rear extension typically takes 10 to 14 weeks from breaking ground to final decorative handover.' },
    ],
  },
  {
    id: 'renovations',
    slug: 'renovations',
    title: 'Full House Renovations',
    shortDescription: 'Complete property overhauls, structural reconfigurations, modern rewiring, replumbing, and interior transformations.',
    fullDescription:
      'Breathe new life into period or dated properties. Our comprehensive renovation service covers full structural reconfiguration, load-bearing wall removal, complete M&E (electrical rewiring and central heating upgrades), acoustic insulation, bespoke joinery, and flawless plaster and flooring finishes.',
    iconName: 'Wrench',
    heroImage: '/images/services/full-house-renovations.png',
    indicativePriceRange: '£60,000 – £200,000+',
    typicalDuration: '12 – 24 weeks',
    keyBenefits: [
      'Modernize property energy efficiency and acoustic performance',
      'Optimize layout flow by removing unnecessary compartmentalized walls',
      'Future-proof electrics, smart home infrastructure, and heating systems',
      'Single accountability project management across all trades',
    ],
    stages: [
      { title: 'Strip-Out & Structural Assessment', description: 'Careful removal of fixtures, plaster, and exploratory inspection of timbers.' },
      { title: 'Structural Alterations', description: 'Chimney breast removals, load-bearing steelwork installation, and subfloor leveling.' },
      { title: 'M&E Infrastructure (First Fix)', description: 'Complete electrical rewiring, plumbing, network cabling, and insulation.' },
      { title: 'Drylining & Plastering', description: 'Acoustic boarding, dot-and-dab, and multi-coat skim plastering.' },
      { title: 'Second Fix & Joinery', description: 'Internal doors, architraves, skirtings, flooring, and bespoke cabinetry.' },
      { title: 'Decoration & Handover', description: 'Mist coats, premium emulsion painting, trade certification, and snagging.' },
    ],
    planningGuidance: 'Internal alterations rarely require planning permission unless the property is a Listed Building or located in a Conservation Area with Article 4 directions.',
    costDrivers: ['Total floor area', 'Subfloor structural repairs', 'Full rewiring & plumbing replacement', 'Heating system (radiators vs underfloor heating)', 'Level of custom joinery and sanitaryware'],
    faqs: [
      { question: 'Is it cheaper to renovate all at once or room by room?', answer: 'A whole-house renovation is significantly more cost-effective per square metre due to consolidated scaffolding, skip hire, trade scheduling, and bulk material ordering.' },
      { question: 'Do you supply Building Control certificates?', answer: 'Yes. All structural changes, electrical works (Part P), and gas installations (Gas Safe) are certified with local authority compliance paperwork provided upon completion.' },
    ],
  },
  {
    id: 'kitchen-renovations',
    slug: 'kitchen-renovations',
    title: 'Kitchen Renovations',
    shortDescription: 'Bespoke culinary spaces, architectural kitchen islands, quartz worktops, and integrated appliances.',
    fullDescription:
      'The heart of any modern home. We deliver turnkey luxury kitchen renovations including structural knock-throughs to create open-plan dining, subfloor heating, designer lighting circuits, bespoke cabinetry installation, and natural stone or composite surfaces.',
    iconName: 'ChefHat',
    heroImage: '/images/services/kitchen-renovations.png',
    indicativePriceRange: '£20,000 – £65,000+',
    typicalDuration: '3 – 6 weeks',
    keyBenefits: [
      'Custom layout tailored to your cooking, dining, and entertaining habits',
      'Premium surfaces: quartz, porcelain, polished concrete, and solid hardwoods',
      'Precision installation with certified plumbing and dedicated electrical rings',
      'Seamless integration with utility rooms and patio access',
    ],
    stages: [
      { title: 'Design & Spatial Planning', description: 'Working triangle optimization, cabinetry layouts, and lighting schematics.' },
      { title: 'Demolition & First Fix', description: 'Removal of old units, pipework rerouting, and appliance power point installation.' },
      { title: 'Flooring & Prep', description: 'Underfloor heating mats, self-leveling screed, and tile/LVT installation.' },
      { title: 'Cabinetry Fitting', description: 'Precision carcass leveling, pantry units, island assembly, and integrated appliances.' },
      { title: 'Worktop Templating & Fit', description: 'Laser templating and seamless installation of quartz or stone worktops.' },
      { title: 'Splashbacks & Final Snagging', description: 'Tiling, silicone sealing, tap connections, and appliance testing.' },
    ],
    planningGuidance: 'Internal kitchen renovations do not require planning permission. Building regulations apply to electrical safety and mechanical ventilation extraction rates.',
    costDrivers: ['Cabinetry build (German/British modular vs bespoke in-frame)', 'Worktop material (laminate vs quartz/dekton)', 'Appliance tiers (Neff, Miele, Bora, Gaggenau)', 'Structural alterations required'],
    faqs: [
      { question: 'Can you relocate our kitchen sink and cooker to an island?', answer: 'Yes. We run recessed waste pipes, water supplies, and floor-channelled electrical circuits or downdraft extraction ducts to island locations.' },
    ],
  },
  {
    id: 'bathroom-renovations',
    slug: 'bathroom-renovations',
    title: 'Bathroom Renovations',
    shortDescription: 'Luxury wet rooms, spa-inspired en-suites, walk-in showers, and bespoke tiling solutions.',
    fullDescription:
      'Transform ordinary bathrooms into private sanctuaries. We design and install waterproofed walk-in wet rooms, freestanding baths, concealed thermostatic valve showers, wall-hung sanitaryware, and precision large-format porcelain tiling.',
    iconName: 'Bath',
    heroImage: '/images/services/bathroom-renovations.png',
    indicativePriceRange: '£12,000 – £35,000+',
    typicalDuration: '2 – 4 weeks',
    keyBenefits: [
      'Complete tanking and waterproofing guarantee against leaks',
      'Concealed cisterns and wall-hung units for a clean, spacious look',
      'Heated towel rails, underfloor warmth, and niche ambient LED lighting',
      'High-pressure water boost pump integration if required',
    ],
    stages: [
      { title: 'Strip Out & Plumbing Prep', description: 'Full clearance, waste pipe realignment, and pressure testing.' },
      { title: 'Tanking & Waterproofing', description: 'Application of waterproof membrane systems to shower zones and wet areas.' },
      { title: 'Tiling & Electrical First Fix', description: 'Underfloor heating, precision laser tiling, and extractor fan ducting.' },
      { title: 'Sanitaryware Installation', description: 'Fitting vanity units, taps, thermostatic valves, and glass screens.' },
    ],
    planningGuidance: 'Bathroom renovations do not require planning permission. Regulated plumbing and electrical works are certified by our team.',
    costDrivers: ['Tile size and material (marble/porcelain)', 'Concealed valve vs exposed bar shower', 'Wet room former installation', 'Custom glass screen fabrication'],
    faqs: [
      { question: 'How do you prevent leaks in wet rooms?', answer: 'We use professional Schluter/Mapei tanking membranes with sealed corner tapes across all wet zones before tiling, backed by our waterproofing guarantee.' },
    ],
  },
  {
    id: 'loft-conversions',
    slug: 'loft-conversions',
    title: 'Loft Conversions',
    shortDescription: 'Transform unutilized attic volume into luxury master suites, dormer bedrooms, or rooftop home offices.',
    fullDescription:
      'Unlock the untapped space at the top of your house. Loft conversions represent the highest ROI per square metre for residential properties. Whether you need a rear dormer, hip-to-gable conversion, or Velux rooflight conversion, we manage steel installation, staircases, insulation, and en-suite bathrooms.',
    iconName: 'Building',
    heroImage: '/images/services/loft-conversions.png',
    indicativePriceRange: '£45,000 – £85,000+',
    typicalDuration: '8 – 12 weeks',
    keyBenefits: [
      'Gain an expansive master bedroom with private en-suite and Juliet balcony',
      'Utilize existing roof footprint without reducing garden space',
      'Substantially increases property valuation',
      'Completed in as little as 8 weeks with external scaffolding access',
    ],
    stages: [
      { title: 'Structural & Steel Design', description: 'Ridge steel and universal floor beam sizing for roof load bearing.' },
      { title: 'Scaffolding & Roof Opening', description: 'External access scaffolding and weather-tight temporary canopy.' },
      { title: 'Steel & Dormer Framing', description: 'Floor joist reinforcement, steel erection, and dormer timber framing.' },
      { title: 'Insulation & Windows', description: 'High-performance PIR thermal insulation, Velux windows, and French/Juliet doors.' },
      { title: 'Staircase & Internal Division', description: 'Matching bespoke staircase installation aligning with existing hall layout.' },
      { title: 'Plumbing, En-Suite & Finishes', description: 'Full first/second fix, plastering, en-suite fit-out, and fire door compliance.' },
    ],
    planningGuidance: 'Most rear dormer conversions up to 40m³ (terraced) or 50m³ (semi-detached/detached) are permitted development provided materials match.',
    costDrivers: ['Conversion type (Velux vs Rear Dormer vs Mansard)', 'Roof pitch and structural steel complexity', 'En-suite bathroom inclusion', 'Bespoke matching staircase'],
    faqs: [
      { question: 'Will a loft conversion reduce ceiling height on the floor below?', answer: 'No, modern structural steel designs support new independent floor joists above the existing ceiling without impacting ceiling height below.' },
    ],
  },
  {
    id: 'garage-conversions',
    slug: 'garage-conversions',
    title: 'Garage Conversions',
    shortDescription: 'Convert neglected garages into functional home offices, gymnasiums, playrooms, or guest bedrooms.',
    fullDescription:
      'Garages are frequently underused storage areas. A garage conversion is a rapid, cost-effective way to add valuable ground-floor living space without extending outward into your garden.',
    iconName: 'Layers',
    heroImage: '/images/services/garage-conversions.png',
    indicativePriceRange: '£15,000 – £35,000+',
    typicalDuration: '3 – 6 weeks',
    keyBenefits: [
      'Cost-effective additional living area',
      'Fast turnaround with minimal household disruption',
      'Increases usable thermal living space and insulation',
    ],
    stages: [
      { title: 'Garage Door Infill', description: 'Replacing garage door with brickwork matching existing house and double-glazed window.' },
      { title: 'Damp Proofing & Floor Raising', description: 'DPM membrane, thermal insulation, and screed level with house floor.' },
      { title: 'Wall & Ceiling Insulation', description: 'Independent stud walls with vapor barriers and acoustic insulation.' },
      { title: 'Electrics, Heating & Finish', description: 'Radiator extension, power rings, spotlighting, and plastering.' },
    ],
    planningGuidance: 'Typically Permitted Development unless council conditions on the original property grant removed parking conversion rights.',
    costDrivers: ['Integral vs detached garage', 'Floor leveling and DPC requirements', 'Window/door infill brick matching', 'Plumbing for en-suite or utility'],
    faqs: [
      { question: 'Do I need planning permission to convert a garage?', answer: 'In over 90% of cases, garage conversions fall under Permitted Development, requiring only Building Regulations sign-off.' },
    ],
  },
  {
    id: 'garden-rooms',
    slug: 'garden-rooms',
    title: 'Garden Rooms & Studios',
    shortDescription: 'Fully insulated, all-season architectural garden offices, studios, entertainment suites, and gyms.',
    fullDescription:
      'Create a secluded sanctuary in your garden. Our bespoke timber-frame garden rooms feature premium composite or Western Red Cedar cladding, aluminium bi-folding doors, full electrical connections with high-speed data links, and all-weather multi-foil insulation.',
    iconName: 'Trees',
    heroImage: '/images/services/garden-rooms.png',
    indicativePriceRange: '£18,000 – £45,000+',
    typicalDuration: '3 – 5 weeks',
    keyBenefits: [
      'Year-round thermal comfort with multi-layer insulation',
      'Zero commute: ideal dedicated workspace separated from family life',
      'No planning permission required in standard gardens',
      'Contemporary finishes with cedar/composite cladding and dark aluminium frames',
    ],
    stages: [
      { title: 'Ground Screw / Concrete Base', description: 'Solid engineered foundation system minimizing lawn disruption.' },
      { title: 'Timber Frame Construction', description: 'Structural insulated timber framing with breathable membranes.' },
      { title: 'EPDM Rubber Roofing', description: 'Continuous single-ply rubber membrane with 25-year lifespan.' },
      { title: 'Cladding & Glazing', description: 'Architectural cladding and double-glazed thermally broken doors.' },
      { title: 'Armoured Electrical Connection', description: 'Direct consumer unit connection with data cabling and heating.' },
    ],
    planningGuidance: 'Outbuildings built under 2.5m maximum height within 2m of a boundary (or under 4m with dual pitch roof) fall strictly within Permitted Development.',
    costDrivers: ['Dimensions and footprint', 'Cladding choice (Cedar, Larch, Composite)', 'Glazing aperture width', 'Electrical trenching distance from main house'],
    faqs: [
      { question: 'Can the garden room be used all year in winter?', answer: 'Yes. Our garden rooms are built to residential house insulation standards with double glazing and climate control heating.' },
    ],
  },
  {
    id: 'driveways',
    slug: 'driveways',
    title: 'Driveways & Paving',
    shortDescription: 'Block paving, resin-bound surfacing, natural stone setts, and durable parking solutions.',
    fullDescription:
      'First impressions count. We construct premium permeable driveways that blend kerb appeal with heavy-load durability. Options include resin-bound aggregates, porcelain driveway paving, traditional clay pavers, and cobblestone granite borders with integrated drainage channels.',
    iconName: 'Car',
    heroImage: '/images/services/driveways.png',
    indicativePriceRange: '£8,000 – £30,000+',
    typicalDuration: '1 – 2 weeks',
    keyBenefits: [
      'Superior kerb appeal and secure off-street parking',
      'SuDS-compliant permeable bases preventing standing surface water',
      'Reinforced sub-bases engineered to prevent sinking or rutting',
      'Full choice of natural stone, resin colours, and edging details',
    ],
    stages: [
      { title: 'Excavation & Sub-Base', description: 'Dig out to 250mm depth and install compacted MOT Type 1 aggregate.' },
      { title: 'Geotextile Membrane & Edgings', description: 'Weed-suppressing membrane and concrete-haunched perimeter curbs.' },
      { title: 'Drainage & Soakaways', description: 'Aco channel drains and soakaway crates ensuring water regulation compliance.' },
      { title: 'Surface Laying & Jointing', description: 'Laying chosen block paving, resin matrix, or stone with kiln-dried sand or resin grout.' },
    ],
    planningGuidance: 'Driveways over 5m² require permeable surfacing or drainage channels diverting rainwater to a lawn or border to avoid planning requirements.',
    costDrivers: ['Square meterage', 'Surface material (resin vs block vs porcelain)', 'Excavation depth and spoil removal', 'Kerb dropping application'],
    faqs: [
      { question: 'Is resin-bound surfacing permeable?', answer: 'Yes, resin-bound systems are 100% permeable and allow rainwater to drain naturally through to the sub-base, complying with SuDS regulations.' },
    ],
  },
  {
    id: 'landscaping',
    slug: 'landscaping',
    title: 'Landscaping & Outdoor Living',
    shortDescription: 'Architectural porcelain patios, composite decking, outdoor kitchens, retaining walls, and bespoke lighting.',
    fullDescription:
      'Extend your interior living space out into the garden. We design and construct contemporary outdoor living environments featuring large-format porcelain paving, composite decks, rendered planters, integrated fire pits, water features, and zoned garden lighting schemes.',
    iconName: 'Sun',
    heroImage: '/images/services/landscaping.png',
    indicativePriceRange: '£10,000 – £50,000+',
    typicalDuration: '2 – 5 weeks',
    keyBenefits: [
      'Seamless flush transitions from interior kitchen/living to patio',
      'Low maintenance porcelain and composite decking materials',
      'Integrated outdoor cooking, seating, and heating zones',
      'Atmospheric low-voltage garden lighting design',
    ],
    stages: [
      { title: 'Garden Design & Levels', description: 'Topographical surveying, level setting, and retaining wall engineering.' },
      { title: 'Earthworks & Base Prep', description: 'Excavation, drainage systems, and concrete/sub-base installation.' },
      { title: 'Hard Landscaping', description: 'Porcelain slab laying with priming slurry, walling, steps, and copings.' },
      { title: 'Carpentry & Lighting', description: 'Decking subframes, screens, pergola construction, and LED wiring.' },
      { title: 'Soft Landscaping', description: 'Lawn preparation, premium turfing, and border planting schemes.' },
    ],
    planningGuidance: 'Patios and landscaping generally do not require planning permission unless significantly raising ground levels or building high boundary walls.',
    costDrivers: ['Area size', 'Porcelain vs Indian Sandstone', 'Decking material (timber vs composite)', 'Retaining walls and terracing required'],
    faqs: [
      { question: 'Can you match the patio tiles to my kitchen floor?', answer: 'Yes, we frequently install matching indoor/outdoor porcelain tiles with continuous flush thresholds for a seamless indoor-outdoor feel.' },
    ],
  },
];
