'use client';

import React from 'react';
import { ProjectState } from '@/types/visualiser-scope';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import {
  FileText,
  Printer,
  Download,
  Share2,
  X,
  CheckCircle2,
  Building,
  Ruler,
  PoundSterling,
} from 'lucide-react';
import { siteConfig } from '@/config/site';

interface BuilderReadyBriefModalProps {
  state: ProjectState;
  isOpen: boolean;
  onClose: () => void;
  onSendToSTContractors: () => void;
}

export function BuilderReadyBriefModal({
  state,
  isOpen,
  onClose,
  onSendToSTContractors,
}: BuilderReadyBriefModalProps) {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const primarySpace = state.spaces[0];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white rounded-3xl max-w-3xl w-full border border-slate-200 shadow-2xl my-8 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="p-6 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-[#FFAA4F] text-slate-950 font-bold flex items-center justify-center shadow-xs">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900 font-heading">
                Builder-Ready Project Brief
              </h2>
              <span className="text-xs text-slate-500">
                Generated by ST Contractors AI Design &amp; Scope Builder
              </span>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-full text-slate-400 hover:text-slate-700 hover:bg-slate-200 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Scrollable Printable Document */}
        <div className="p-6 sm:p-8 overflow-y-auto space-y-6 text-xs text-slate-700 print:p-0">
          {/* Document Title Banner */}
          <div className="p-5 rounded-2xl bg-slate-900 text-white space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#FFAA4F]">
                Project Reference #{state.projectId}
              </span>
              <span className="text-[10px] text-slate-400">
                Date: {new Date(state.createdAt).toLocaleDateString()}
              </span>
            </div>
            <h1 className="text-xl font-bold font-heading text-white">
              {state.interpretedIntent}
            </h1>
            <div className="text-xs text-slate-300">
              Location: {state.property.location.value} • Property: {state.property.type.value} ({state.property.era.value})
            </div>
          </div>

          {/* Key Dimensions & Spaces */}
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
              1. Dimensions &amp; Room Scale
            </h3>
            {primarySpace && (
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                <div>
                  <span className="text-slate-400 block text-[10px]">Room Area</span>
                  <strong className="text-slate-900">{primarySpace.areaM2.value} m²</strong>
                </div>
                <div>
                  <span className="text-slate-400 block text-[10px]">Length × Width</span>
                  <strong className="text-slate-900">{primarySpace.lengthM.value}m × {primarySpace.widthM.value}m</strong>
                </div>
                <div>
                  <span className="text-slate-400 block text-[10px]">Ceiling Height</span>
                  <strong className="text-slate-900">{primarySpace.heightM.value}m</strong>
                </div>
                <div>
                  <span className="text-slate-400 block text-[10px]">Estimated Range</span>
                  <strong className="text-slate-900 text-[#FFAA4F]">{state.budgetAlignment.indicativeCostRange.formatted}</strong>
                </div>
              </div>
            )}
          </div>

          {/* Trade Scope Summary */}
          <div className="space-y-2">
            <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
              2. Confirmed Trade Scope ({state.scopeOfWorks.filter(s => s.included).length} Items)
            </h3>
            <div className="space-y-1.5">
              {state.scopeOfWorks.filter(s => s.included).map((s) => (
                <div key={s.id} className="p-2.5 rounded-xl bg-slate-50 border border-slate-200/80 flex items-start gap-2">
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600 shrink-0 mt-0.5" />
                  <div>
                    <strong className="text-slate-900">{s.title}</strong>
                    <p className="text-[11px] text-slate-600 leading-normal">{s.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Key Quantities */}
          <div className="space-y-2">
            <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
              3. Estimated Bill of Quantities
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {state.calculatedQuantities.filter(q => q.totalWithWaste > 0).map((q) => (
                <div key={q.id} className="p-2.5 rounded-xl bg-slate-50 border border-slate-200">
                  <span className="text-[10px] text-slate-400 block">{q.item}</span>
                  <span className="font-bold text-slate-900 text-xs mt-0.5 block">{q.totalWithWaste} {q.unit}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Modal Footer Actions */}
        <div className="p-5 border-t border-slate-200 bg-slate-50 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex gap-2 w-full sm:w-auto">
            <Button
              type="button"
              onClick={handlePrint}
              variant="outline"
              size="sm"
              className="text-xs font-bold bg-white"
              leftIcon={<Printer className="h-3.5 w-3.5" />}
            >
              Print / Save PDF
            </Button>
          </div>

          <Button
            type="button"
            onClick={onSendToSTContractors}
            variant="primary"
            size="md"
            className="w-full sm:w-auto text-xs sm:text-sm font-extrabold bg-[#FFAA4F] hover:bg-[#F59E3F] text-slate-950 border border-[#E69335] shadow-md"
          >
            Send Project Brief to ST Contractors
          </Button>
        </div>
      </div>
    </div>
  );
}
