import React from 'react';
import type { Metadata } from 'next';
import { Container } from '@/components/ui/Container';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { FileText, Shield, AlertCircle, Scale, CheckCircle2, Clock } from 'lucide-react';
import { siteConfig } from '@/config/site';

export const metadata: Metadata = {
  title: 'Terms of Business & Website Terms | ST CONTRACTORS',
  description: `Terms of business, formal quotation validity periods, milestone payment structures, and client warranties for ${siteConfig.name}.`,
};

export default function TermsOfBusinessPage() {
  const lastUpdated = 'February 2026';

  return (
    <div className="py-16 sm:py-24 bg-white text-slate-900 text-left">
      <Container size="md">
        {/* Header */}
        <div className="space-y-4 pb-10 border-b border-slate-200">
          <Badge variant="brand" className="bg-amber-100 text-amber-900 border-amber-300 text-xs">
            <Scale className="h-3.5 w-3.5 mr-1" />
            Standard Construction Terms &amp; Conditions
          </Badge>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold font-heading text-slate-900 tracking-tight">
            Terms of Business
          </h1>
          <p className="text-sm text-slate-500">
            Last Updated: {lastUpdated} • {siteConfig.company.name} (Registered in England &amp; Wales No. {siteConfig.company.registrationNumber})
          </p>
        </div>

        {/* Content Sections */}
        <div className="mt-10 space-y-10 text-slate-700 text-sm leading-relaxed">
          {/* 1. Introduction & Scope */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <FileText className="h-5 w-5 text-amber-600" />
              1. Introduction &amp; Agreement
            </h2>
            <p>
              These Terms of Business govern the use of the {siteConfig.name} website, digital project planning tools, calculators, and the preliminary quotation and contracting process for residential construction, house extension, and renovation services provided by <strong>{siteConfig.company.name}</strong> (&quot;the Contractor&quot;).
            </p>
            <p>
              By accessing our website or requesting project estimates, you agree to these Terms. Formal construction works will be governed by a separate, bespoke written building contract (e.g. FMB or JCT Homeowner Contract) signed prior to site mobilisation.
            </p>
          </section>

          {/* 2. Preliminary Estimates vs. Formal Quotations */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <Clock className="h-5 w-5 text-amber-600" />
              2. Indicative Estimates &amp; Formal Quotation Validity
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-1">
              <Card className="p-4 bg-slate-50 border-slate-200 space-y-1">
                <strong className="text-slate-900 font-heading block text-xs uppercase">Online Planning Estimates</strong>
                <span className="text-xs text-slate-600 leading-relaxed">
                  All figures generated by our online calculators, AI visualiser, and project planners represent preliminary guide estimates based on typical London ground and property conditions. They do not constitute a binding legal tender.
                </span>
              </Card>
              <Card className="p-4 bg-slate-50 border-slate-200 space-y-1">
                <strong className="text-slate-900 font-heading block text-xs uppercase">Formal Written Quotes</strong>
                <span className="text-xs text-slate-600 leading-relaxed">
                  Formal written quotations issued following a senior surveyor site inspection and structural drawing review remain valid for <strong>30 calendar days</strong> from the date of issue.
                </span>
              </Card>
            </div>
          </section>

          {/* 3. Milestone Payment Schedules & Deposits */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <Shield className="h-5 w-5 text-amber-600" />
              3. Milestone Payment Structure
            </h2>
            <p>
              To protect both homeowner and contractor, our construction contracts operate on a transparent, staged milestone payment schedule tied strictly to physical on-site progress:
            </p>
            <ul className="list-disc pl-6 space-y-1.5 text-slate-600">
              <li><strong>Initial Deposit:</strong> A standard 5% to 10% mobilisation deposit upon contract execution to reserve construction scheduling and procurement of long-lead materials (e.g. bespoke glazing, structural steel).</li>
              <li><strong>Staged Interim Valuations:</strong> Pre-agreed weekly or fortnightly stage payments released only after completed milestones (e.g. Foundations &amp; Drainage sign-off, Structural Steelwork install, First-Fix M&amp;E, Plastering, Second-Fix Joinery).</li>
              <li><strong>Final Retention:</strong> A 2.5% to 5% retention sum retained by the client until final snagging completion and Local Authority Building Control sign-off.</li>
            </ul>
          </section>

          {/* 4. Statutory Approvals & Client Responsibilities */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-amber-600" />
              4. Client Statutory Obligations
            </h2>
            <p>Unless expressly included within our full turnkey design-and-build package, the client is responsible for ensuring:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-slate-600">
              <li><strong>Planning &amp; Permitted Development:</strong> Obtaining required Local Authority Planning Consents or Certificates of Lawfulness prior to construction commencement.</li>
              <li><strong>Party Wall Act 1996:</strong> Serving statutory Party Wall notices and securing written Party Wall Agreements / Awards with adjoining neighbours where excavations or boundary wall works occur.</li>
              <li><strong>Thames Water Clearances:</strong> Securing formal Build-Over agreements if building within 3 metres of a public sewer.</li>
              <li><strong>Site Access &amp; Parking:</strong> Providing reasonable access to water, electricity, and facilitating resident parking permits or skip placement permits where applicable.</li>
            </ul>
          </section>

          {/* 5. Variations & Unforeseen Site Conditions */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <AlertCircle className="h-5 w-5 text-amber-600" />
              5. Variations &amp; Unforeseen Strip-Out Discoveries
            </h2>
            <p>
              In period London residential properties (Victorian, Edwardian, Georgian), concealed structural defects (e.g. historic dry rot, unbonded chimney flues, subfloor subsidence, or lead plumbing) may only become visible upon destructive strip-out.
            </p>
            <p>
              No additional works will be carried out without a formal <strong>Written Variation Order</strong> agreed and signed by both parties, detailing the exact scope, material specification, and cost impact before execution.
            </p>
          </section>

          {/* 6. Warranties & Insurance */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900">
              6. Warranties &amp; Insurance Protection
            </h2>
            <p>
              {siteConfig.company.name} maintains comprehensive insurance coverage throughout the project lifecycle:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-slate-600">
              <li>£10,000,000 Public Liability Insurance.</li>
              <li>£10,000,000 Employers&apos; Liability Insurance.</li>
              <li>All-Risks Contractors Insurance covering works in progress.</li>
              <li>10-Year Insurance-Backed Structural Warranty on qualifying major extensions and renovations.</li>
            </ul>
          </section>

          {/* 7. Governing Law */}
          <section className="p-6 bg-slate-50 border border-slate-200 rounded-2xl space-y-2">
            <h2 className="text-base font-bold font-heading text-slate-900">
              7. Governing Law &amp; Jurisdiction
            </h2>
            <p className="text-xs text-slate-600 leading-relaxed">
              These Terms and any contractual agreements entered into with {siteConfig.company.name} shall be governed by and construed in accordance with the laws of <strong>England and Wales</strong>, and both parties submit to the exclusive jurisdiction of the English courts.
            </p>
          </section>
        </div>
      </Container>
    </div>
  );
}
