import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Container } from '@/components/ui/Container';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { AlertTriangle, ShieldCheck, Scale, Calculator, Building, ArrowRight } from 'lucide-react';
import { siteConfig } from '@/config/site';

export const metadata: Metadata = {
  title: 'Calculator & AI Planning Legal Disclaimer | ST CONTRACTORS',
  description: `Statutory disclaimers and consumer guidance regarding construction calculators, automated project planners, and architectural visualisations on ${siteConfig.name}.`,
};

export default function LegalDisclaimerPage() {
  const lastUpdated = 'February 2026';

  return (
    <div className="py-16 sm:py-24 bg-white text-slate-900 text-left">
      <Container size="md">
        {/* Header */}
        <div className="space-y-4 pb-10 border-b border-slate-200">
          <Badge variant="brand" className="bg-amber-100 text-amber-900 border-amber-300 text-xs">
            <Scale className="h-3.5 w-3.5 mr-1" />
            Consumer Protection from Unfair Trading Regulations (CPRs) Compliance
          </Badge>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold font-heading text-slate-900 tracking-tight">
            Calculator &amp; Planning Legal Disclaimer
          </h1>
          <p className="text-sm text-slate-500">
            Last Updated: {lastUpdated} • {siteConfig.company.name}
          </p>
        </div>

        {/* Content Sections */}
        <div className="mt-10 space-y-10 text-slate-700 text-sm leading-relaxed">
          {/* Highlight Warning Alert */}
          <div className="p-5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-950 space-y-2">
            <div className="flex items-center gap-2 font-bold text-base font-heading text-amber-900">
              <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0" />
              <span>Important Notice: Indicative Guide Estimates Only</span>
            </div>
            <p className="text-xs leading-relaxed text-amber-900/90">
              All financial estimates, material quantities, construction timelines, and 3D architectural visualisations provided across this website (including our 20 construction calculators, Typeform planner, and AI Visualiser) are designed solely as preliminary educational planning guides. They do <strong>not</strong> constitute a binding commercial offer, formal quotation, or legal commitment to undertake works at the indicated figures.
            </p>
          </div>

          {/* 1. Nature of Online Calculators */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <Calculator className="h-5 w-5 text-amber-600" />
              1. Basis of Cost Calculations
            </h2>
            <p>
              Our calculators and pricing algorithms utilise verified London and South East construction industry benchmarks, current trade labour rates, and merchant material prices. However, actual project costs vary substantially depending on property-specific factors that cannot be assessed online, including:
            </p>
            <ul className="list-disc pl-6 space-y-1.5 text-slate-600">
              <li><strong>Subterranean Ground Conditions:</strong> High-shrinkage London clay, historic fill, tree root zones, or high water tables requiring engineered piled foundations or underpinning rather than standard 1m strip foundations.</li>
              <li><strong>Structural Load Paths:</strong> Existing masonry bearing capacity, chimney breast loads, and required RSJ steel beam spans.</li>
              <li><strong>Drainage &amp; Utilities:</strong> Position of public sewers (Thames Water build-over requirements), capacity of electrical consumer units, and gas meter supply pressures.</li>
              <li><strong>Site Accessibility:</strong> Terraced properties with no side access requiring internal material barrowing, parking suspension zones, or craneage over rooftops.</li>
            </ul>
          </section>

          {/* 2. Professional & Statutory Exclusions */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <Building className="h-5 w-5 text-amber-600" />
              2. Professional Disciplines &amp; Statutory Authority
            </h2>
            <p>
              Information published on this website or generated by our AI planning assistant does <strong>not</strong> substitute for formal professional advice from licensed specialists. Nothing on this website should be interpreted as:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-1">
              <Card className="p-4 bg-slate-50 border-slate-200 space-y-1">
                <strong className="text-slate-900 font-heading block text-xs uppercase">Structural Engineering</strong>
                <span className="text-xs text-slate-600 leading-relaxed">
                  Calculations on this website do not replace structural calculation packages signed by a chartered structural engineer (MIStructE / CEng) for Building Regulations submission.
                </span>
              </Card>
              <Card className="p-4 bg-slate-50 border-slate-200 space-y-1">
                <strong className="text-slate-900 font-heading block text-xs uppercase">Statutory Party Wall Awards</strong>
                <span className="text-xs text-slate-600 leading-relaxed">
                  Advice regarding the Party Wall etc. Act 1996 does not replace statutory notices served by an appointed Member of the Faculty of Party Wall Surveyors (MFPWS).
                </span>
              </Card>
              <Card className="p-4 bg-slate-50 border-slate-200 space-y-1">
                <strong className="text-slate-900 font-heading block text-xs uppercase">Planning Permission</strong>
                <span className="text-xs text-slate-600 leading-relaxed">
                  Permitted Development assessments are indicative; formal confirmation requires a Certificate of Lawfulness from your Local Planning Authority.
                </span>
              </Card>
              <Card className="p-4 bg-slate-50 border-slate-200 space-y-1">
                <strong className="text-slate-900 font-heading block text-xs uppercase">Gas &amp; Electrical Safety</strong>
                <span className="text-xs text-slate-600 leading-relaxed">
                  All M&amp;E guidance is preliminary; physical installation sign-offs are issued on-site exclusively by Gas Safe Registered and NICEIC certified engineers.
                </span>
              </Card>
            </div>
          </section>

          {/* 3. Formal Process to Obtain a Fixed Price Quote */}
          <section className="p-6 bg-slate-900 text-white rounded-3xl space-y-4">
            <h2 className="text-lg font-bold font-heading text-white">
              How to Obtain a Formal, Binding Fixed-Price Contract
            </h2>
            <p className="text-xs text-slate-300 leading-relaxed">
              To convert your preliminary online plan into a guaranteed fixed-price construction contract, our senior surveyor will conduct a comprehensive physical site inspection, inspect architectural drawings, and prepare a detailed room-by-room specification.
            </p>
            <div className="flex flex-wrap items-center gap-3 pt-2">
              <Button
                href="/plan-my-project"
                variant="primary"
                size="sm"
                className="bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs"
                rightIcon={<ArrowRight className="h-4 w-4" />}
              >
                Plan My Project
              </Button>
              <Button
                href="/contact?type=consultation"
                variant="outline"
                size="sm"
                className="border-slate-700 text-slate-200 hover:bg-slate-800 text-xs"
              >
                Book Surveyor Consultation
              </Button>
            </div>
          </section>
        </div>
      </Container>
    </div>
  );
}
